version: '3'
services:
  backend:
    image: mr-backend:latest
    ports:
      - 5000:5000
    container_name: backend
    build:
      context: meme-reviewer-backend/
  frontend:
    image: mr-frontend:latest
    ports:
      - 3000:3000
    container_name: frontend
    build:
      context: meme-reviewer-frontend/